name: Petstore Swagger API Automation

on:
  push:
    branches:
      - Feature/ManasviGanu-CBATest
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Run Behave Tests with Allure
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o allure_results ./features

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: /allure_results

      - name: Generate Allure Report (Optional)
        run: |
          allure generate reports/allure-results --clean -o reports/allure-report

      - name: Upload Allure Report (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: /allure_reports
